name: Validate Kubernetes Manifests
on:
  workflow_call:
    secrets:
      KUBE_CONFIG_SECRET_NAME:
        required: true
    inputs:
      kubernetes-manifest-files:
        required: true
        type: string
      kubernetes-manifest-env:
          required: false
          type: string

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest 
    
    strategy:
      matrix:
        kubectl-version: [v1.24.10]
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Setup Kubectl version
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ matrix.kubectl-version }}
    
          
      - name: Create list of manifest files
        run: |
          echo "LIST_OF_FILES_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo "${{ inputs.kubernetes-manifest-files }}" | while read -r line ; do echo $line; done >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Set Parameters
        id: set_params
        run: |
          echo "${{ inputs.kubernetes-manifest-files }}" > ${{ env.FILES_PATH }}
          echo "${{ kubernetes-manifest-env }}" > ${{ env.PLACEHOLDERS_PATH }}
        env:
          FILES_PATH: ${{ github.workspace }}/files.txt
          PLACEHOLDERS_PATH: ${{ github.workspace }}/placeholders.txt
          
      - name: Replace Placeholders
        run: |
          files=$(cat ${{ env.FILES_PATH }})
          placeholders=$(cat ${{ env.PLACEHOLDERS_PATH }})

          IFS=$'\n' read -r -a files_array <<< "$files"
          IFS=$'\n' read -r -a placeholders_array <<< "$placeholders"

          for file in "${files_array[@]}"
          do
            content=$(cat "$file")

            for placeholder in "${placeholders_array[@]}"
            do
              IFS='=' read -r -a placeholder_parts <<< "$placeholder"
              search="${placeholder_parts[0]}"
              replace="${placeholder_parts[1]}"

              content=${content//$search/$replace}
            done

            echo "$content" > "$file"
          done    
      
      - name: Show updated files
        run: |
          git status --porcelain
          
      - uses: Azure/k8s-set-context@v3
        with:
          kubeconfig:  ${{ secrets.KUBE_CONFIG_SECRET_NAME }}
          
      - name: validate 
        uses: Azure/k8s-lint@v2.0
        with:
          lintType: dryrun
          manifests: |
             ${{ env.LIST_OF_FILES_ENV_VAR }}

