name: Validate Kubernetes Manifests
on:
  workflow_call:
    secrets:
      KUBE_CONFIG_SECRET_NAME:
        required: true
    inputs:
      kubernetes-manifest-files:
        required: true
        type: string
      kubernetes-manifest-env:
        required: false
        type: string

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        kubectl-version: [v1.24.10]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Setup Kubectl version
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ matrix.kubectl-version }}
          
      - name: Create list of manifest files
        run: |
          echo "LIST_OF_FILES_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo "${{ inputs.kubernetes-manifest-files }}" | while read -r line ; do echo $line; done >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: replace place holder values in kubernetes manifests
        if: "${{ inputs.kubernetes-manifest-env != '' }}"
        uses: LSVH/gha-replace-placeholders@v1
        with:
          include:
            ${{ inputs.kubernetes-manifest-files }}
          placeholders: |
            ${{ inputs.kubernetes-manifest-env }}

      - name: Set kube context
        uses: Azure/k8s-set-context@v3
        with:
          kubeconfig:  ${{ secrets.KUBE_CONFIG_SECRET_NAME }}
          
      - name: validate manifests
        uses: Azure/k8s-lint@v2.0
        with:
          lintType: dryrun
          manifests: |
            ${{ env.LIST_OF_FILES_ENV_VAR }}
