name: Validate Kubernetes Manifests

on:
  workflow_call:
    secrets:
      KUBE_CONFIG_SECRET_NAME:
        required: true
    inputs:
      kubernetes-manifest-files:
        required: true
        type: string
      kubernetes-manifest-env:
        required: false
        type: string

jobs:
  create-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Create matrix
        id: create-matrix
        run: |
          echo "KUBERNETES_FILE=$(echo '${{ inputs.kubernetes-manifest-files }}' | jq -R .)" >> $GITHUB_ENV
          echo "KUBERNETES_ENV=$(echo '${{ inputs.kubernetes-manifest-env }}' | jq -R .)" >> $GITHUB_ENV

  validate-k8s-manifests:
    needs: create-matrix
    runs-on: ubuntu-latest
    env:
      KUBERNETES_FILE: ${{ needs.create-matrix.outputs.KUBERNETES_FILE }}
      KUBERNETES_ENV: ${{ needs.create-matrix.outputs.KUBERNETES_ENV }}

    strategy:
      matrix:
        kubernetes-file: ${{ fromJSON(env.KUBERNETES_FILE) }}
        kubernetes-env: ${{ fromJSON(env.KUBERNETES_ENV) }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Kubectl version
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ matrix.kubectl-version }}

      - name: Create list of manifest files
        run: |
          echo "LIST_OF_FILES_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo "${{ join(matrix.kubernetes-file, '\n') }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: datamonsters/replace-action@v2
        with:
          files: ${{ join(matrix.kubernetes-file, '\n') }}
          replacements: ${{ join(matrix.kubernetes-env, '\n') }}

      - uses: Azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_SECRET_NAME }}

      - name: validate
        uses: Azure/k8s-lint@v2.0
        with:
          lintType: dryrun
          manifests: ${{ env.LIST_OF_FILES_ENV_VAR }}
