name: Validate Kubernetes Manifests
on:
  workflow_call:
    inputs:
      kubernetes-manifest:
        required: true
        type: string

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl-version: [v1.24.10]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Setup Kubectl version
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ matrix.kubectl-version }}
      - name: Create list of modified files
        id: modified_files_list
        run: |
          for file in ${{ inputs.kubernetes-manifest}}
          do
           echo $file
          done
          
      - name: validate manifests
        uses: Azure/k8s-lint@v2.0
        with:
          lintType: kubeval
          manifests: |
             ${{ steps.modified_files_list.outputs.stringList }}
