name: Validate Kubernetes Manifests
on:
  workflow_call:
    secrets:
      kubeconfig:
        required: true
    inputs:
      kubernetes-manifest-files:
        required: true
        type: string

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest 
    
    strategy:
      matrix:
        kubectl-version: [v1.24.10]
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:

      - name: Setup Kubectl version
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ matrix.kubectl-version }}
    
          
      - name: Create list of manifest files
        run: |
          echo "LIST_OF_FILES_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo "${{ inputs.kubernetes-manifest-files }}" | while read -r line ; do echo $line; done >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: Azure/k8s-set-context@v3
        with:
          kubeconfig:  ${{ secrets.kubeconfig }}
          
      - name: validate 
        uses: Azure/k8s-lint@v2.0
        with:
          lintType: dryrun
          manifests: |
             ${{ env.LIST_OF_FILES_ENV_VAR }}

