name: Validate Kubernetes Manifests
on:
  workflow_call:
    inputs:
      kubernetes-manifest:
        required: true
        type: string

jobs:
  validate-k8s-manifests:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    strategy:
      matrix:
        kubectl-version: [v1.24.10]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Setup Kubectl version
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ matrix.kubectl-version }}
          
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.1
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "kubernetes/"
          ext: ".yml"   
        
      - name: validate manifests
        uses: Azure/k8s-lint@v2.0
        with:
          lintType: kubeval
          manifests: |
             ${{ fromJson(steps.list-files.outputs.paths) }}
